# Generated by Django 6.1.1 on 2026-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
