# Generated by Django 6.1.1 on 2026-10-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
