# Generated by Django 6.1.1 on 2026-10-04 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('campaign', models.CharField(blank=True, help_text='Where the customer came from', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.customer')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='customer_notes', to='accounts.employee')),
            ],
            options={
                'db_table': 'customer_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('interaction_date', models.DateTimeField()),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='accounts.employee')),
            ],
            options={
                'db_table': 'interaction',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('opportunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed', 'Closed')], default='lead', max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=0, help_text='Chance of winning, 0 to 100 (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=10)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.customer')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='accounts.employee')),
            ],
            options={
                'db_table': 'opportunity',
                'ordering': ['-expected_close_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer')),
            ],
            options={
                'db_table': 'contact',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('customer',), name='unique_primary_contact_per_customer')],
            },
        ),
    ]
